#! /usr/bin/python2.7 -tt
import sys
from socket import *

def main():
    RECEIVING_SIZE = 1024
    INIT_COUNT = 0
    port = int(sys.argv[1])
    server_request_counter = [INIT_COUNT]

    server_socket = socket()
    server_socket.connect(('localhost', port))

    while True:
        data_received = receive_from_socket(server_socket, RECEIVING_SIZE)
        response = process_data_received(data_received, server_request_counter, server_socket)
        server_socket.sendall(response)

def receive_from_socket(server_socket, RECEIVING_SIZE):
    END_OF_HTTP_REQUEST = "\r\n\r\n"
    data_received = ""
    while(END_OF_HTTP_REQUEST not in data_received):
        data_received+= server_socket.recv(RECEIVING_SIZE)

    return data_received

def process_data_received(data_received, server_request_counter, server_socket):
    get_line_of_address = data_received.split('\r\n')[0]
    if "counter " in get_line_of_address:
        server_request_counter[0] += 1
        http_response = """HTTP/1.0 200 OK\r\nContent-Type: text/html\r\nContent-Length: """ + \
                        str(len(str(server_request_counter[0]))) + """\r\n\r\n""" + \
                        str(server_request_counter[0]) + """\r\n\r\n"""
    else:
        http_response = """HTTP/1.1 404 Not Found\r\nContent-type: text/html\r\nContent-length: \ 113\r\n\r\n
        <html><head><title>Not Found</title></head><body>\r\n
        Sorry, the object you requested was not found.\r\n</body></html>\r\n\r\n"""

    return http_response

if __name__ == "__main__":
    main()